export const Sys = {
  APP_NAME : 'MoxMobile',
  VERSION: 'v1.0.0',
  BUILD_DATE: '2018.5.8',
  REPO_SOURCE: 'https://github.com/mockingbox/moxmobile',
  FETCHING_MATCHES : 'FETCHING_MATCHES',
  FETCHING_MATCHES_SUCCESS : 'FETCHING_MATCHES_SUCCESS',
  FETCHING_MATCHES_FAILURE : 'FETCHING_MATCHES_FAILURE',
  FETCHING_NEWS : 'FETCHING_NEWS',
  FETCHING_NEWS_SUCCESS : 'FETCHING_NEWS_SUCCESS',
  FETCHING_NEWS_FAILURE : 'FETCHING_NEWS_FAILURE',
  FETCHING_PEOPLE : 'FETCHING_PEOPLE',
  FETCHING_PEOPLE_SUCCESS : 'FETCHING_PEOPLE_SUCCESS',
  FETCHING_PEOPLE_FAILURE : 'FETCHING_PEOPLE_FAILURE',
  FETCHING_PLAYERS : 'FETCHING_PLAYERS',
  PLAYERS_ADD_NEW : 'PLAYERS_ADD_NEW',
  FETCHING_PLAYERS_SUCCESS : 'FETCHING_PLAYERS_SUCCESS',
  FETCHING_PLAYERS_FAILURE : 'FETCHING_PLAYERS_FAILURE',
  FETCHING_TEAMS : 'FETCHING_TEAMS',
  FETCHING_TEAMS_SUCCESS : 'FETCHING_TEAMS_SUCCESS',
  FETCHING_TEAMS_FAILURE : 'FETCHING_TEAMS_FAILURE',
  SHOT_MISS: "MISS",
  SHOT_SCRATCH: "SCRATCH",
  SHOT_DEFENSIVE: "DEFENSIVE",
  SHOT_TURN: "TURN",
  SHOT_WIN: "WIN",
  SHOT_BREAK_RUN: "BREAK_RUN",
  SHOT_TIMEOUT: "TIMEOUT",
  SHOT_SCRATCH8: "SCRATCH8",
  SHOT_WRONG_POCKET8: "WRONG_POCKET8"
};

export const Cfg = {
  MAX_ITEMS : 1000
}
